hatMe:
    enable: true
    allowed: 
    - 1
    - 2
    - 3
    - 4
    - 5
    - 12
    - 13
    - 14
    - 15
    - 17
    - 18
    - 20
    - 22
    - 23
    - 24
    - 25
    - 35
    - 41
    - 42
    - 44
    - 45
    - 46
    - 47
    - 48
    - 49
    - 52
    - 54
    - 57
    - 58
    - 80
    - 81
    - 82
    - 87
    - 88
    - 89
    - 91
    - 98
    - 103
    - 112
    opnorestrict: true
    notAllowedMsg: "You do not have permission"